# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1412, 767)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(1000)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_threshold = QtWidgets.QWidget()
        self.tab_threshold.setObjectName("tab_threshold")
        self.tab_threshold_layout = QtWidgets.QGridLayout(self.tab_threshold)
        self.tab_threshold_layout.setContentsMargins(10, 10, 10, 10)
        self.tab_threshold_layout.setSpacing(10)
        self.tab_threshold_layout.setObjectName("tab_threshold_layout")
        self.frame = QtWidgets.QFrame(self.tab_threshold)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_edit_input_path = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_input_path.setFont(font)
        self.line_edit_input_path.setToolTipDuration(1000)
        self.line_edit_input_path.setReadOnly(True)
        self.line_edit_input_path.setObjectName("line_edit_input_path")
        self.horizontalLayout_5.addWidget(self.line_edit_input_path)
        self.pushbutton_input_path_browser = QtWidgets.QPushButton(self.groupBox)
        self.pushbutton_input_path_browser.setToolTipDuration(1000)
        self.pushbutton_input_path_browser.setObjectName("pushbutton_input_path_browser")
        self.horizontalLayout_5.addWidget(self.pushbutton_input_path_browser)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_threshold = QtWidgets.QSlider(self.groupBox_2)
        self.slider_threshold.setEnabled(False)
        self.slider_threshold.setToolTipDuration(2000)
        self.slider_threshold.setMaximum(255)
        self.slider_threshold.setProperty("value", 50)
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.horizontalLayout_4.addWidget(self.slider_threshold)
        self.line_edit_threshold = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_edit_threshold.setEnabled(False)
        self.line_edit_threshold.setToolTipDuration(1500)
        self.line_edit_threshold.setObjectName("line_edit_threshold")
        self.horizontalLayout_4.addWidget(self.line_edit_threshold)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushbutton_otsu = QtWidgets.QPushButton(self.groupBox_2)
        self.pushbutton_otsu.setEnabled(False)
        self.pushbutton_otsu.setToolTipDuration(1000)
        self.pushbutton_otsu.setObjectName("pushbutton_otsu")
        self.horizontalLayout_3.addWidget(self.pushbutton_otsu)
        self.pushbutton_entropy = QtWidgets.QPushButton(self.groupBox_2)
        self.pushbutton_entropy.setEnabled(False)
        self.pushbutton_entropy.setToolTipDuration(1000)
        self.pushbutton_entropy.setObjectName("pushbutton_entropy")
        self.horizontalLayout_3.addWidget(self.pushbutton_entropy)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit_export_path = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_export_path.setFont(font)
        self.line_edit_export_path.setToolTipDuration(1000)
        self.line_edit_export_path.setReadOnly(True)
        self.line_edit_export_path.setObjectName("line_edit_export_path")
        self.horizontalLayout_2.addWidget(self.line_edit_export_path)
        self.pushbutton_export_path_browser = QtWidgets.QPushButton(self.groupBox_3)
        self.pushbutton_export_path_browser.setEnabled(True)
        self.pushbutton_export_path_browser.setToolTipDuration(1000)
        self.pushbutton_export_path_browser.setObjectName("pushbutton_export_path_browser")
        self.horizontalLayout_2.addWidget(self.pushbutton_export_path_browser)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushbutton_export = QtWidgets.QPushButton(self.groupBox_3)
        self.pushbutton_export.setEnabled(False)
        self.pushbutton_export.setToolTipDuration(1000)
        self.pushbutton_export.setObjectName("pushbutton_export")
        self.horizontalLayout.addWidget(self.pushbutton_export)
        self.pushbutton_sendto1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushbutton_sendto1.setToolTipDuration(2000)
        self.pushbutton_sendto1.setObjectName("pushbutton_sendto1")
        self.horizontalLayout.addWidget(self.pushbutton_sendto1)
        self.pushbutton_reset = QtWidgets.QPushButton(self.groupBox_3)
        self.pushbutton_reset.setToolTipDuration(1500)
        self.pushbutton_reset.setObjectName("pushbutton_reset")
        self.horizontalLayout.addWidget(self.pushbutton_reset)
        self.pushbutton_exit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushbutton_exit.setToolTipDuration(1000)
        self.pushbutton_exit.setObjectName("pushbutton_exit")
        self.horizontalLayout.addWidget(self.pushbutton_exit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tab_threshold_layout.addWidget(self.frame, 0, 0, 1, 2)
        self.graphics_view_source_image = QtWidgets.QGraphicsView(self.tab_threshold)
        self.graphics_view_source_image.setToolTipDuration(1000)
        self.graphics_view_source_image.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_source_image.setLineWidth(1)
        self.graphics_view_source_image.setObjectName("graphics_view_source_image")
        self.tab_threshold_layout.addWidget(self.graphics_view_source_image, 1, 0, 1, 1)
        self.graphics_view_histgram = QtChart.QChartView(self.tab_threshold)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view_histgram.sizePolicy().hasHeightForWidth())
        self.graphics_view_histgram.setSizePolicy(sizePolicy)
        self.graphics_view_histgram.setToolTipDuration(1000)
        self.graphics_view_histgram.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_histgram.setFrameShadow(QtWidgets.QFrame.Raised)
        brush = QtGui.QBrush(QtGui.QColor(255, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphics_view_histgram.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphics_view_histgram.setForegroundBrush(brush)
        self.graphics_view_histgram.setObjectName("graphics_view_histgram")
        self.tab_threshold_layout.addWidget(self.graphics_view_histgram, 1, 1, 1, 1)
        self.graphics_view_binary_image = QtWidgets.QGraphicsView(self.tab_threshold)
        self.graphics_view_binary_image.setToolTipDuration(1000)
        self.graphics_view_binary_image.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_binary_image.setObjectName("graphics_view_binary_image")
        self.tab_threshold_layout.addWidget(self.graphics_view_binary_image, 0, 2, 2, 1)
        self.tab_threshold_layout.setColumnStretch(0, 2)
        self.tab_threshold_layout.setColumnStretch(1, 3)
        self.tab_threshold_layout.setColumnStretch(2, 4)
        self.tab_threshold_layout.setRowStretch(0, 1)
        self.tab_threshold_layout.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_threshold, "")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.tab_filter_layout = QtWidgets.QGridLayout(self.tab_filters)
        self.tab_filter_layout.setContentsMargins(10, 10, 10, 10)
        self.tab_filter_layout.setSpacing(10)
        self.tab_filter_layout.setObjectName("tab_filter_layout")
        self.frame_2 = QtWidgets.QFrame(self.tab_filters)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_13 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.line_edit_input_path2 = QtWidgets.QLineEdit(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_input_path2.setFont(font)
        self.line_edit_input_path2.setToolTipDuration(1000)
        self.line_edit_input_path2.setReadOnly(True)
        self.line_edit_input_path2.setObjectName("line_edit_input_path2")
        self.horizontalLayout_26.addWidget(self.line_edit_input_path2)
        self.pushbutton_input_path_browser2 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushbutton_input_path_browser2.setToolTipDuration(1000)
        self.pushbutton_input_path_browser2.setObjectName("pushbutton_input_path_browser2")
        self.horizontalLayout_26.addWidget(self.pushbutton_input_path_browser2)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.verticalLayout_13.addWidget(self.groupBox_13)
        self.groupbox_filter_processing = QtWidgets.QGroupBox(self.frame_2)
        self.groupbox_filter_processing.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_filter_processing.setFont(font)
        self.groupbox_filter_processing.setObjectName("groupbox_filter_processing")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupbox_filter_processing)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.groupbox_filter_processing)
        self.line.setEnabled(True)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 3, 1)
        self.frame_filters = QtWidgets.QFrame(self.groupbox_filter_processing)
        self.frame_filters.setEnabled(False)
        self.frame_filters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_filters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_filters.setObjectName("frame_filters")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_filters)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radiobutton_direct01 = QtWidgets.QRadioButton(self.frame_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radiobutton_direct01.setFont(font)
        self.radiobutton_direct01.setToolTipDuration(1500)
        self.radiobutton_direct01.setCheckable(True)
        self.radiobutton_direct01.setChecked(True)
        self.radiobutton_direct01.setObjectName("radiobutton_direct01")
        self.gridLayout_3.addWidget(self.radiobutton_direct01, 1, 0, 1, 1)
        self.radiobutton_direct02 = QtWidgets.QRadioButton(self.frame_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobutton_direct02.setFont(font)
        self.radiobutton_direct02.setToolTipDuration(1500)
        self.radiobutton_direct02.setObjectName("radiobutton_direct02")
        self.gridLayout_3.addWidget(self.radiobutton_direct02, 1, 1, 1, 1)
        self.radiobutton_amplitude = QtWidgets.QRadioButton(self.frame_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobutton_amplitude.setFont(font)
        self.radiobutton_amplitude.setToolTipDuration(1500)
        self.radiobutton_amplitude.setChecked(False)
        self.radiobutton_amplitude.setObjectName("radiobutton_amplitude")
        self.gridLayout_3.addWidget(self.radiobutton_amplitude, 1, 2, 1, 1)
        self.combobox_filters = QtWidgets.QComboBox(self.frame_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_filters.setFont(font)
        self.combobox_filters.setToolTipDuration(3000)
        self.combobox_filters.setObjectName("combobox_filters")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.combobox_filters.addItem("")
        self.gridLayout_3.addWidget(self.combobox_filters, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame_filters, 1, 0, 3, 1)
        self.frame_gaussian_sigma = QtWidgets.QFrame(self.groupbox_filter_processing)
        self.frame_gaussian_sigma.setEnabled(True)
        self.frame_gaussian_sigma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_gaussian_sigma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_gaussian_sigma.setObjectName("frame_gaussian_sigma")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_gaussian_sigma)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_gaussian_sigma = QtWidgets.QLabel(self.frame_gaussian_sigma)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_gaussian_sigma.setFont(font)
        self.label_gaussian_sigma.setObjectName("label_gaussian_sigma")
        self.horizontalLayout_9.addWidget(self.label_gaussian_sigma)
        self.slider_gaussian_sigma = QtWidgets.QSlider(self.frame_gaussian_sigma)
        self.slider_gaussian_sigma.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_gaussian_sigma.setFont(font)
        self.slider_gaussian_sigma.setToolTipDuration(1500)
        self.slider_gaussian_sigma.setMinimum(1)
        self.slider_gaussian_sigma.setMaximum(30)
        self.slider_gaussian_sigma.setSingleStep(1)
        self.slider_gaussian_sigma.setPageStep(1)
        self.slider_gaussian_sigma.setProperty("value", 12)
        self.slider_gaussian_sigma.setOrientation(QtCore.Qt.Horizontal)
        self.slider_gaussian_sigma.setObjectName("slider_gaussian_sigma")
        self.horizontalLayout_9.addWidget(self.slider_gaussian_sigma)
        self.line_edit_gaussian_sigma = QtWidgets.QLineEdit(self.frame_gaussian_sigma)
        self.line_edit_gaussian_sigma.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_gaussian_sigma.setFont(font)
        self.line_edit_gaussian_sigma.setToolTipDuration(1500)
        self.line_edit_gaussian_sigma.setMaxLength(15)
        self.line_edit_gaussian_sigma.setCursorPosition(3)
        self.line_edit_gaussian_sigma.setObjectName("line_edit_gaussian_sigma")
        self.horizontalLayout_9.addWidget(self.line_edit_gaussian_sigma)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 6)
        self.horizontalLayout_9.setStretch(2, 1)
        self.gridLayout_2.addWidget(self.frame_gaussian_sigma, 3, 2, 1, 2)
        self.frame_filter_size = QtWidgets.QFrame(self.groupbox_filter_processing)
        self.frame_filter_size.setEnabled(True)
        self.frame_filter_size.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_filter_size.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_filter_size.setObjectName("frame_filter_size")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_filter_size)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_filter_size = QtWidgets.QLabel(self.frame_filter_size)
        self.label_filter_size.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_filter_size.setFont(font)
        self.label_filter_size.setObjectName("label_filter_size")
        self.horizontalLayout_8.addWidget(self.label_filter_size)
        self.slider_filter_size = QtWidgets.QSlider(self.frame_filter_size)
        self.slider_filter_size.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_filter_size.setFont(font)
        self.slider_filter_size.setToolTipDuration(1000)
        self.slider_filter_size.setMinimum(0)
        self.slider_filter_size.setMaximum(5)
        self.slider_filter_size.setSingleStep(1)
        self.slider_filter_size.setPageStep(1)
        self.slider_filter_size.setProperty("value", 1)
        self.slider_filter_size.setTracking(True)
        self.slider_filter_size.setOrientation(QtCore.Qt.Horizontal)
        self.slider_filter_size.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_filter_size.setTickInterval(0)
        self.slider_filter_size.setObjectName("slider_filter_size")
        self.horizontalLayout_8.addWidget(self.slider_filter_size)
        self.line_edit_filter_size = QtWidgets.QLineEdit(self.frame_filter_size)
        self.line_edit_filter_size.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_filter_size.setFont(font)
        self.line_edit_filter_size.setToolTipDuration(1000)
        self.line_edit_filter_size.setMaxLength(15)
        self.line_edit_filter_size.setCursorPosition(1)
        self.line_edit_filter_size.setObjectName("line_edit_filter_size")
        self.horizontalLayout_8.addWidget(self.line_edit_filter_size)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 6)
        self.horizontalLayout_8.setStretch(2, 1)
        self.gridLayout_2.addWidget(self.frame_filter_size, 2, 2, 1, 2)
        self.verticalLayout_13.addWidget(self.groupbox_filter_processing)
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.line_edit_export_path2 = QtWidgets.QLineEdit(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_export_path2.setFont(font)
        self.line_edit_export_path2.setToolTipDuration(1000)
        self.line_edit_export_path2.setReadOnly(True)
        self.line_edit_export_path2.setObjectName("line_edit_export_path2")
        self.horizontalLayout_29.addWidget(self.line_edit_export_path2)
        self.pushbutton_export_path_browser2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushbutton_export_path_browser2.setEnabled(True)
        self.pushbutton_export_path_browser2.setToolTipDuration(1000)
        self.pushbutton_export_path_browser2.setObjectName("pushbutton_export_path_browser2")
        self.horizontalLayout_29.addWidget(self.pushbutton_export_path_browser2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushbutton_export2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushbutton_export2.setEnabled(False)
        self.pushbutton_export2.setToolTipDuration(1000)
        self.pushbutton_export2.setObjectName("pushbutton_export2")
        self.horizontalLayout_30.addWidget(self.pushbutton_export2)
        self.pushbutton_sendto2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushbutton_sendto2.setToolTipDuration(2000)
        self.pushbutton_sendto2.setObjectName("pushbutton_sendto2")
        self.horizontalLayout_30.addWidget(self.pushbutton_sendto2)
        self.pushbutton_reset2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushbutton_reset2.setToolTipDuration(1500)
        self.pushbutton_reset2.setObjectName("pushbutton_reset2")
        self.horizontalLayout_30.addWidget(self.pushbutton_reset2)
        self.pushbutton_exit2 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushbutton_exit2.setToolTipDuration(1000)
        self.pushbutton_exit2.setObjectName("pushbutton_exit2")
        self.horizontalLayout_30.addWidget(self.pushbutton_exit2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_30)
        self.verticalLayout_13.addWidget(self.groupBox_15)
        self.tab_filter_layout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.graphics_view_filters_image = QtWidgets.QGraphicsView(self.tab_filters)
        self.graphics_view_filters_image.setToolTipDuration(1000)
        self.graphics_view_filters_image.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_filters_image.setObjectName("graphics_view_filters_image")
        self.tab_filter_layout.addWidget(self.graphics_view_filters_image, 0, 2, 2, 1)
        self.graphics_view_source_image2 = QtWidgets.QGraphicsView(self.tab_filters)
        self.graphics_view_source_image2.setToolTipDuration(1000)
        self.graphics_view_source_image2.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_source_image2.setObjectName("graphics_view_source_image2")
        self.tab_filter_layout.addWidget(self.graphics_view_source_image2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_filters)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.table_filter = QtWidgets.QTableWidget(self.frame_4)
        self.table_filter.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.table_filter.setFont(font)
        self.table_filter.setToolTipDuration(1000)
        self.table_filter.setFrameShape(QtWidgets.QFrame.Box)
        self.table_filter.setLineWidth(1)
        self.table_filter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_filter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_filter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_filter.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.table_filter.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_filter.setGridStyle(QtCore.Qt.SolidLine)
        self.table_filter.setObjectName("table_filter")
        self.table_filter.setColumnCount(0)
        self.table_filter.setRowCount(0)
        self.table_filter.horizontalHeader().setVisible(False)
        self.table_filter.horizontalHeader().setHighlightSections(True)
        self.table_filter.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.table_filter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 4)
        self.horizontalLayout_7.setStretch(2, 1)
        self.tab_filter_layout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.tab_filter_layout.setColumnStretch(0, 2)
        self.tab_filter_layout.setColumnStretch(1, 3)
        self.tab_filter_layout.setColumnStretch(2, 4)
        self.tab_filter_layout.setRowStretch(0, 1)
        self.tab_filter_layout.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_morph_oper = QtWidgets.QWidget()
        self.tab_morph_oper.setObjectName("tab_morph_oper")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_morph_oper)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_morph_oper_function_area = QtWidgets.QFrame(self.tab_morph_oper)
        self.frame_morph_oper_function_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_morph_oper_function_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_morph_oper_function_area.setObjectName("frame_morph_oper_function_area")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_morph_oper_function_area)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_14 = QtWidgets.QGroupBox(self.frame_morph_oper_function_area)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.line_edit_input_path3 = QtWidgets.QLineEdit(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_input_path3.setFont(font)
        self.line_edit_input_path3.setToolTipDuration(1000)
        self.line_edit_input_path3.setReadOnly(True)
        self.line_edit_input_path3.setObjectName("line_edit_input_path3")
        self.horizontalLayout_28.addWidget(self.line_edit_input_path3)
        self.pushbutton_input_path_browser3 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushbutton_input_path_browser3.setToolTipDuration(1000)
        self.pushbutton_input_path_browser3.setObjectName("pushbutton_input_path_browser3")
        self.horizontalLayout_28.addWidget(self.pushbutton_input_path_browser3)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.verticalLayout_14.addWidget(self.groupBox_14)
        self.groupbox_se_processing = QtWidgets.QGroupBox(self.frame_morph_oper_function_area)
        self.groupbox_se_processing.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_se_processing.setFont(font)
        self.groupbox_se_processing.setObjectName("groupbox_se_processing")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupbox_se_processing)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_morph_oper = QtWidgets.QFrame(self.groupbox_se_processing)
        self.frame_morph_oper.setEnabled(False)
        self.frame_morph_oper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_morph_oper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_morph_oper.setObjectName("frame_morph_oper")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_morph_oper)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.combobox_morph_oper = QtWidgets.QComboBox(self.frame_morph_oper)
        self.combobox_morph_oper.setToolTipDuration(2000)
        self.combobox_morph_oper.setObjectName("combobox_morph_oper")
        self.combobox_morph_oper.addItem("")
        self.combobox_morph_oper.addItem("")
        self.combobox_morph_oper.addItem("")
        self.combobox_morph_oper.addItem("")
        self.gridLayout_5.addWidget(self.combobox_morph_oper, 0, 0, 1, 1)
        self.checkbox_show_diff = QtWidgets.QCheckBox(self.frame_morph_oper)
        self.checkbox_show_diff.setToolTipDuration(2000)
        self.checkbox_show_diff.setObjectName("checkbox_show_diff")
        self.gridLayout_5.addWidget(self.checkbox_show_diff, 0, 1, 1, 1)
        self.combobox_se = QtWidgets.QComboBox(self.frame_morph_oper)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_se.setFont(font)
        self.combobox_se.setToolTipDuration(3000)
        self.combobox_se.setObjectName("combobox_se")
        self.combobox_se.addItem("")
        self.combobox_se.addItem("")
        self.combobox_se.addItem("")
        self.combobox_se.addItem("")
        self.gridLayout_5.addWidget(self.combobox_se, 1, 0, 1, 1)
        self.checkbox_se_regular = QtWidgets.QCheckBox(self.frame_morph_oper)
        self.checkbox_se_regular.setObjectName("checkbox_se_regular")
        self.gridLayout_5.addWidget(self.checkbox_se_regular, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_4.addWidget(self.frame_morph_oper, 0, 0, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.groupbox_se_processing)
        self.line_2.setEnabled(True)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 1, 2, 1)
        self.frame_se_width = QtWidgets.QFrame(self.groupbox_se_processing)
        self.frame_se_width.setEnabled(True)
        self.frame_se_width.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_se_width.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_se_width.setObjectName("frame_se_width")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_se_width)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_se_width = QtWidgets.QLabel(self.frame_se_width)
        self.label_se_width.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_se_width.setFont(font)
        self.label_se_width.setObjectName("label_se_width")
        self.horizontalLayout_11.addWidget(self.label_se_width)
        self.slider_se_width = QtWidgets.QSlider(self.frame_se_width)
        self.slider_se_width.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_se_width.setFont(font)
        self.slider_se_width.setToolTipDuration(2000)
        self.slider_se_width.setMinimum(0)
        self.slider_se_width.setMaximum(6)
        self.slider_se_width.setSingleStep(1)
        self.slider_se_width.setPageStep(1)
        self.slider_se_width.setProperty("value", 2)
        self.slider_se_width.setTracking(True)
        self.slider_se_width.setOrientation(QtCore.Qt.Horizontal)
        self.slider_se_width.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_se_width.setTickInterval(0)
        self.slider_se_width.setObjectName("slider_se_width")
        self.horizontalLayout_11.addWidget(self.slider_se_width)
        self.line_edit_se_width = QtWidgets.QLineEdit(self.frame_se_width)
        self.line_edit_se_width.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_se_width.setFont(font)
        self.line_edit_se_width.setToolTipDuration(1500)
        self.line_edit_se_width.setMaxLength(15)
        self.line_edit_se_width.setCursorPosition(1)
        self.line_edit_se_width.setObjectName("line_edit_se_width")
        self.horizontalLayout_11.addWidget(self.line_edit_se_width)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 6)
        self.horizontalLayout_11.setStretch(2, 1)
        self.gridLayout_4.addWidget(self.frame_se_width, 0, 2, 1, 1)
        self.frame_se_height = QtWidgets.QFrame(self.groupbox_se_processing)
        self.frame_se_height.setEnabled(True)
        self.frame_se_height.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_se_height.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_se_height.setObjectName("frame_se_height")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_se_height)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_se_height = QtWidgets.QLabel(self.frame_se_height)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_se_height.setFont(font)
        self.label_se_height.setObjectName("label_se_height")
        self.horizontalLayout_10.addWidget(self.label_se_height)
        self.slider_se_height = QtWidgets.QSlider(self.frame_se_height)
        self.slider_se_height.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.slider_se_height.setFont(font)
        self.slider_se_height.setToolTipDuration(2000)
        self.slider_se_height.setMinimum(0)
        self.slider_se_height.setMaximum(6)
        self.slider_se_height.setSingleStep(1)
        self.slider_se_height.setPageStep(1)
        self.slider_se_height.setProperty("value", 2)
        self.slider_se_height.setOrientation(QtCore.Qt.Horizontal)
        self.slider_se_height.setObjectName("slider_se_height")
        self.horizontalLayout_10.addWidget(self.slider_se_height)
        self.line_edit_se_height = QtWidgets.QLineEdit(self.frame_se_height)
        self.line_edit_se_height.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_se_height.setFont(font)
        self.line_edit_se_height.setToolTipDuration(1500)
        self.line_edit_se_height.setMaxLength(15)
        self.line_edit_se_height.setCursorPosition(1)
        self.line_edit_se_height.setObjectName("line_edit_se_height")
        self.horizontalLayout_10.addWidget(self.line_edit_se_height)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 6)
        self.horizontalLayout_10.setStretch(2, 1)
        self.gridLayout_4.addWidget(self.frame_se_height, 1, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 2)
        self.verticalLayout_14.addWidget(self.groupbox_se_processing)
        self.groupBox_16 = QtWidgets.QGroupBox(self.frame_morph_oper_function_area)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.line_edit_export_path3 = QtWidgets.QLineEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_export_path3.setFont(font)
        self.line_edit_export_path3.setToolTipDuration(1000)
        self.line_edit_export_path3.setReadOnly(True)
        self.line_edit_export_path3.setObjectName("line_edit_export_path3")
        self.horizontalLayout_31.addWidget(self.line_edit_export_path3)
        self.pushbutton_export_path_browser3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushbutton_export_path_browser3.setEnabled(True)
        self.pushbutton_export_path_browser3.setToolTipDuration(1000)
        self.pushbutton_export_path_browser3.setObjectName("pushbutton_export_path_browser3")
        self.horizontalLayout_31.addWidget(self.pushbutton_export_path_browser3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushbutton_export3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushbutton_export3.setEnabled(False)
        self.pushbutton_export3.setToolTipDuration(1000)
        self.pushbutton_export3.setObjectName("pushbutton_export3")
        self.horizontalLayout_32.addWidget(self.pushbutton_export3)
        self.pushbutton_sendto3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushbutton_sendto3.setToolTipDuration(2000)
        self.pushbutton_sendto3.setObjectName("pushbutton_sendto3")
        self.horizontalLayout_32.addWidget(self.pushbutton_sendto3)
        self.pushbutton_reset3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushbutton_reset3.setToolTipDuration(1500)
        self.pushbutton_reset3.setObjectName("pushbutton_reset3")
        self.horizontalLayout_32.addWidget(self.pushbutton_reset3)
        self.pushbutton_exit3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushbutton_exit3.setToolTipDuration(1000)
        self.pushbutton_exit3.setObjectName("pushbutton_exit3")
        self.horizontalLayout_32.addWidget(self.pushbutton_exit3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_32)
        self.verticalLayout_14.addWidget(self.groupBox_16)
        self.gridLayout_6.addWidget(self.frame_morph_oper_function_area, 0, 0, 1, 2)
        self.graphics_view_morph_oper_image = QtWidgets.QGraphicsView(self.tab_morph_oper)
        self.graphics_view_morph_oper_image.setToolTipDuration(1500)
        self.graphics_view_morph_oper_image.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_morph_oper_image.setObjectName("graphics_view_morph_oper_image")
        self.gridLayout_6.addWidget(self.graphics_view_morph_oper_image, 0, 2, 2, 1)
        self.graphics_view_source_image3 = QtWidgets.QGraphicsView(self.tab_morph_oper)
        self.graphics_view_source_image3.setToolTipDuration(1000)
        self.graphics_view_source_image3.setObjectName("graphics_view_source_image3")
        self.gridLayout_6.addWidget(self.graphics_view_source_image3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_morph_oper)
        self.frame_5.setEnabled(True)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setHorizontalSpacing(0)
        self.gridLayout_12.setVerticalSpacing(7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushbutton_set_origin = QtWidgets.QPushButton(self.frame_5)
        self.pushbutton_set_origin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushbutton_set_origin.setFont(font)
        self.pushbutton_set_origin.setToolTipDuration(1000)
        self.pushbutton_set_origin.setObjectName("pushbutton_set_origin")
        self.gridLayout_12.addWidget(self.pushbutton_set_origin, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushbutton_cancel_set_origin = QtWidgets.QPushButton(self.frame_5)
        self.pushbutton_cancel_set_origin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushbutton_cancel_set_origin.setFont(font)
        self.pushbutton_cancel_set_origin.setToolTipDuration(1000)
        self.pushbutton_cancel_set_origin.setObjectName("pushbutton_cancel_set_origin")
        self.gridLayout_12.addWidget(self.pushbutton_cancel_set_origin, 2, 2, 1, 1)
        self.table_se = QtWidgets.QTableWidget(self.frame_5)
        self.table_se.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.table_se.setFont(font)
        self.table_se.setToolTipDuration(1000)
        self.table_se.setFrameShape(QtWidgets.QFrame.Box)
        self.table_se.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_se.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_se.setObjectName("table_se")
        self.table_se.setColumnCount(0)
        self.table_se.setRowCount(0)
        self.table_se.horizontalHeader().setVisible(False)
        self.table_se.verticalHeader().setVisible(False)
        self.gridLayout_12.addWidget(self.table_se, 0, 1, 3, 1)
        self.gridLayout_12.setColumnStretch(0, 1)
        self.gridLayout_12.setColumnStretch(1, 6)
        self.gridLayout_12.setColumnStretch(2, 1)
        self.gridLayout_6.addWidget(self.frame_5, 1, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.gridLayout_6.setColumnStretch(1, 3)
        self.gridLayout_6.setColumnStretch(2, 4)
        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_morph_oper, "")
        self.tab_morph_funs = QtWidgets.QWidget()
        self.tab_morph_funs.setObjectName("tab_morph_funs")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_morph_funs)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graphics_view_morph_funs_image = QtWidgets.QGraphicsView(self.tab_morph_funs)
        self.graphics_view_morph_funs_image.setToolTipDuration(2000)
        self.graphics_view_morph_funs_image.setFrameShape(QtWidgets.QFrame.Box)
        self.graphics_view_morph_funs_image.setObjectName("graphics_view_morph_funs_image")
        self.gridLayout_9.addWidget(self.graphics_view_morph_funs_image, 0, 2, 2, 1)
        self.graphics_view_source_image4 = QtWidgets.QGraphicsView(self.tab_morph_funs)
        self.graphics_view_source_image4.setToolTipDuration(1000)
        self.graphics_view_source_image4.setObjectName("graphics_view_source_image4")
        self.gridLayout_9.addWidget(self.graphics_view_source_image4, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_morph_funs)
        self.frame_6.setEnabled(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 1)
        self.graphics_view_marker = MyGraphicsView(self.frame_6)
        self.graphics_view_marker.setToolTipDuration(2000)
        self.graphics_view_marker.setObjectName("graphics_view_marker")
        self.gridLayout_7.addWidget(self.graphics_view_marker, 0, 1, 4, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 2, 1, 1)
        self.combobox_marker_shape = QtWidgets.QComboBox(self.frame_6)
        self.combobox_marker_shape.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.combobox_marker_shape.setFont(font)
        self.combobox_marker_shape.setToolTipDuration(1000)
        self.combobox_marker_shape.setObjectName("combobox_marker_shape")
        self.combobox_marker_shape.addItem("")
        self.combobox_marker_shape.addItem("")
        self.combobox_marker_shape.addItem("")
        self.gridLayout_7.addWidget(self.combobox_marker_shape, 1, 2, 1, 1)
        self.pushbutton_set_marker = QtWidgets.QPushButton(self.frame_6)
        self.pushbutton_set_marker.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushbutton_set_marker.setFont(font)
        self.pushbutton_set_marker.setToolTipDuration(1500)
        self.pushbutton_set_marker.setObjectName("pushbutton_set_marker")
        self.gridLayout_7.addWidget(self.pushbutton_set_marker, 2, 2, 1, 1)
        self.pushbutton_cancel_set_marker = QtWidgets.QPushButton(self.frame_6)
        self.pushbutton_cancel_set_marker.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushbutton_cancel_set_marker.setFont(font)
        self.pushbutton_cancel_set_marker.setToolTipDuration(1500)
        self.pushbutton_cancel_set_marker.setObjectName("pushbutton_cancel_set_marker")
        self.gridLayout_7.addWidget(self.pushbutton_cancel_set_marker, 3, 2, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 4)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.gridLayout_9.addWidget(self.frame_6, 1, 1, 1, 1)
        self.frame_morph_oper_function_area_2 = QtWidgets.QFrame(self.tab_morph_funs)
        self.frame_morph_oper_function_area_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_morph_oper_function_area_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_morph_oper_function_area_2.setObjectName("frame_morph_oper_function_area_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_morph_oper_function_area_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame_morph_oper_function_area_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.line_edit_input_path4 = QtWidgets.QLineEdit(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_input_path4.setFont(font)
        self.line_edit_input_path4.setToolTipDuration(1000)
        self.line_edit_input_path4.setReadOnly(True)
        self.line_edit_input_path4.setObjectName("line_edit_input_path4")
        self.horizontalLayout_34.addWidget(self.line_edit_input_path4)
        self.pushbutton_input_path_browser4 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushbutton_input_path_browser4.setToolTipDuration(1000)
        self.pushbutton_input_path_browser4.setObjectName("pushbutton_input_path_browser4")
        self.horizontalLayout_34.addWidget(self.pushbutton_input_path_browser4)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.verticalLayout_17.addWidget(self.groupBox_17)
        self.groupbox_morph_funs_processing = QtWidgets.QGroupBox(self.frame_morph_oper_function_area_2)
        self.groupbox_morph_funs_processing.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_morph_funs_processing.setFont(font)
        self.groupbox_morph_funs_processing.setObjectName("groupbox_morph_funs_processing")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupbox_morph_funs_processing)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_3 = QtWidgets.QFrame(self.groupbox_morph_funs_processing)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkbox_animation = QtWidgets.QCheckBox(self.frame_3)
        self.checkbox_animation.setEnabled(False)
        self.checkbox_animation.setToolTipDuration(1000)
        self.checkbox_animation.setObjectName("checkbox_animation")
        self.gridLayout_8.addWidget(self.checkbox_animation, 1, 1, 1, 1)
        self.radiobutton_skeleton_reconstruction = QtWidgets.QRadioButton(self.frame_3)
        self.radiobutton_skeleton_reconstruction.setToolTipDuration(1000)
        self.radiobutton_skeleton_reconstruction.setObjectName("radiobutton_skeleton_reconstruction")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radiobutton_skeleton_reconstruction)
        self.gridLayout_8.addWidget(self.radiobutton_skeleton_reconstruction, 2, 0, 1, 1)
        self.radiobutton_distance_transfrom = QtWidgets.QRadioButton(self.frame_3)
        self.radiobutton_distance_transfrom.setToolTipDuration(1000)
        self.radiobutton_distance_transfrom.setChecked(True)
        self.radiobutton_distance_transfrom.setObjectName("radiobutton_distance_transfrom")
        self.buttonGroup.addButton(self.radiobutton_distance_transfrom)
        self.gridLayout_8.addWidget(self.radiobutton_distance_transfrom, 0, 0, 1, 1)
        self.radiobutton_skeleton = QtWidgets.QRadioButton(self.frame_3)
        self.radiobutton_skeleton.setToolTipDuration(1000)
        self.radiobutton_skeleton.setObjectName("radiobutton_skeleton")
        self.buttonGroup.addButton(self.radiobutton_skeleton)
        self.gridLayout_8.addWidget(self.radiobutton_skeleton, 1, 0, 1, 1)
        self.combobox_distance_trans_mode = QtWidgets.QComboBox(self.frame_3)
        self.combobox_distance_trans_mode.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_distance_trans_mode.setFont(font)
        self.combobox_distance_trans_mode.setToolTipDuration(1000)
        self.combobox_distance_trans_mode.setObjectName("combobox_distance_trans_mode")
        self.combobox_distance_trans_mode.addItem("")
        self.combobox_distance_trans_mode.addItem("")
        self.combobox_distance_trans_mode.addItem("")
        self.gridLayout_8.addWidget(self.combobox_distance_trans_mode, 0, 1, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.line_3 = QtWidgets.QFrame(self.groupbox_morph_funs_processing)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_12.addWidget(self.line_3)
        self.frame_morph_oper_2 = QtWidgets.QFrame(self.groupbox_morph_funs_processing)
        self.frame_morph_oper_2.setEnabled(True)
        self.frame_morph_oper_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_morph_oper_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_morph_oper_2.setObjectName("frame_morph_oper_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_morph_oper_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.combobox_morph_reconstrction = QtWidgets.QComboBox(self.frame_morph_oper_2)
        self.combobox_morph_reconstrction.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_morph_reconstrction.setFont(font)
        self.combobox_morph_reconstrction.setToolTipDuration(1000)
        self.combobox_morph_reconstrction.setObjectName("combobox_morph_reconstrction")
        self.combobox_morph_reconstrction.addItem("")
        self.combobox_morph_reconstrction.addItem("")
        self.combobox_morph_reconstrction.addItem("")
        self.gridLayout.addWidget(self.combobox_morph_reconstrction, 1, 1, 1, 1)
        self.radiobutton_edge_detection = QtWidgets.QRadioButton(self.frame_morph_oper_2)
        self.radiobutton_edge_detection.setToolTipDuration(1500)
        self.radiobutton_edge_detection.setObjectName("radiobutton_edge_detection")
        self.buttonGroup.addButton(self.radiobutton_edge_detection)
        self.gridLayout.addWidget(self.radiobutton_edge_detection, 0, 0, 1, 1)
        self.combobox_edge_detection = QtWidgets.QComboBox(self.frame_morph_oper_2)
        self.combobox_edge_detection.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_edge_detection.setFont(font)
        self.combobox_edge_detection.setToolTipDuration(1000)
        self.combobox_edge_detection.setObjectName("combobox_edge_detection")
        self.combobox_edge_detection.addItem("")
        self.combobox_edge_detection.addItem("")
        self.combobox_edge_detection.addItem("")
        self.gridLayout.addWidget(self.combobox_edge_detection, 0, 1, 1, 1)
        self.radiobutton_morph_reconstruction = QtWidgets.QRadioButton(self.frame_morph_oper_2)
        self.radiobutton_morph_reconstruction.setToolTipDuration(3000)
        self.radiobutton_morph_reconstruction.setObjectName("radiobutton_morph_reconstruction")
        self.buttonGroup.addButton(self.radiobutton_morph_reconstruction)
        self.gridLayout.addWidget(self.radiobutton_morph_reconstruction, 1, 0, 1, 1)
        self.combobox_gradient = QtWidgets.QComboBox(self.frame_morph_oper_2)
        self.combobox_gradient.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_gradient.setFont(font)
        self.combobox_gradient.setToolTipDuration(1000)
        self.combobox_gradient.setObjectName("combobox_gradient")
        self.combobox_gradient.addItem("")
        self.combobox_gradient.addItem("")
        self.gridLayout.addWidget(self.combobox_gradient, 2, 1, 1, 1)
        self.radiobutton_gradient = QtWidgets.QRadioButton(self.frame_morph_oper_2)
        self.radiobutton_gradient.setToolTipDuration(1500)
        self.radiobutton_gradient.setObjectName("radiobutton_gradient")
        self.buttonGroup.addButton(self.radiobutton_gradient)
        self.gridLayout.addWidget(self.radiobutton_gradient, 2, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_morph_oper_2)
        self.verticalLayout_17.addWidget(self.groupbox_morph_funs_processing)
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_morph_oper_function_area_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.line_edit_export_path4 = QtWidgets.QLineEdit(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.line_edit_export_path4.setFont(font)
        self.line_edit_export_path4.setToolTipDuration(1000)
        self.line_edit_export_path4.setReadOnly(True)
        self.line_edit_export_path4.setObjectName("line_edit_export_path4")
        self.horizontalLayout_35.addWidget(self.line_edit_export_path4)
        self.pushbutton_export_path_browser4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushbutton_export_path_browser4.setEnabled(True)
        self.pushbutton_export_path_browser4.setToolTipDuration(1000)
        self.pushbutton_export_path_browser4.setObjectName("pushbutton_export_path_browser4")
        self.horizontalLayout_35.addWidget(self.pushbutton_export_path_browser4)
        self.verticalLayout_18.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.pushbutton_export4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushbutton_export4.setEnabled(False)
        self.pushbutton_export4.setToolTipDuration(1000)
        self.pushbutton_export4.setObjectName("pushbutton_export4")
        self.horizontalLayout_36.addWidget(self.pushbutton_export4)
        self.pushbutton_sendto4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushbutton_sendto4.setToolTipDuration(2000)
        self.pushbutton_sendto4.setObjectName("pushbutton_sendto4")
        self.horizontalLayout_36.addWidget(self.pushbutton_sendto4)
        self.pushbutton_reset4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushbutton_reset4.setToolTipDuration(1500)
        self.pushbutton_reset4.setObjectName("pushbutton_reset4")
        self.horizontalLayout_36.addWidget(self.pushbutton_reset4)
        self.pushbutton_exit4 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushbutton_exit4.setToolTipDuration(3000)
        self.pushbutton_exit4.setStatusTip("")
        self.pushbutton_exit4.setObjectName("pushbutton_exit4")
        self.horizontalLayout_36.addWidget(self.pushbutton_exit4)
        self.verticalLayout_18.addLayout(self.horizontalLayout_36)
        self.verticalLayout_17.addWidget(self.groupBox_18)
        self.gridLayout_9.addWidget(self.frame_morph_oper_function_area_2, 0, 0, 1, 2)
        self.gridLayout_9.setColumnStretch(0, 2)
        self.gridLayout_9.setColumnStretch(1, 3)
        self.gridLayout_9.setColumnStretch(2, 4)
        self.gridLayout_9.setRowStretch(0, 1)
        self.gridLayout_9.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_morph_funs, "")
        self.horizontalLayout_13.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1412, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setShortcut("")
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_2)
        self.menuEdit.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.combobox_filters.setCurrentIndex(0)
        self.combobox_se.setCurrentIndex(0)
        self.combobox_distance_trans_mode.setCurrentIndex(0)
        self.combobox_morph_reconstrction.setCurrentIndex(0)
        self.combobox_edge_detection.setCurrentIndex(0)
        self.combobox_gradient.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Image"))
        self.line_edit_input_path.setToolTip(_translate("MainWindow", "Input image path."))
        self.line_edit_input_path.setStatusTip(_translate("MainWindow", "Input image path."))
        self.pushbutton_input_path_browser.setToolTip(_translate("MainWindow", "Choose input image path."))
        self.pushbutton_input_path_browser.setStatusTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Threshold Processing"))
        self.slider_threshold.setToolTip(_translate("MainWindow", "Slider for setting threshold between 0 and 255."))
        self.slider_threshold.setStatusTip(_translate("MainWindow", "Slider for setting threshold between 0 and 255."))
        self.line_edit_threshold.setToolTip(_translate("MainWindow", "Text editor for setting threshold between 0 and 255."))
        self.line_edit_threshold.setStatusTip(_translate("MainWindow", "Text editor for setting threshold between 0 and 255."))
        self.line_edit_threshold.setText(_translate("MainWindow", "50"))
        self.pushbutton_otsu.setToolTip(_translate("MainWindow", "Apply otsu algorithm."))
        self.pushbutton_otsu.setStatusTip(_translate("MainWindow", "Apply otsu algorithm."))
        self.pushbutton_otsu.setText(_translate("MainWindow", "Otsu"))
        self.pushbutton_entropy.setToolTip(_translate("MainWindow", "Apply entropy algorithm."))
        self.pushbutton_entropy.setStatusTip(_translate("MainWindow", "Apply entropy algorithm."))
        self.pushbutton_entropy.setText(_translate("MainWindow", "Entropy"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Export and Output"))
        self.line_edit_export_path.setToolTip(_translate("MainWindow", "Export image path."))
        self.line_edit_export_path.setStatusTip(_translate("MainWindow", "Export image path."))
        self.pushbutton_export_path_browser.setToolTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser.setStatusTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser.setText(_translate("MainWindow", "..."))
        self.pushbutton_export.setToolTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export.setStatusTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export.setText(_translate("MainWindow", "Export"))
        self.pushbutton_sendto1.setToolTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto1.setStatusTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto1.setText(_translate("MainWindow", "Send to..."))
        self.pushbutton_reset.setToolTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset.setStatusTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset.setText(_translate("MainWindow", "Reset"))
        self.pushbutton_exit.setToolTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit.setStatusTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit.setText(_translate("MainWindow", "Exit"))
        self.graphics_view_source_image.setToolTip(_translate("MainWindow", "Source image."))
        self.graphics_view_source_image.setStatusTip(_translate("MainWindow", "Source image."))
        self.graphics_view_source_image.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Source image</p></body></html>"))
        self.graphics_view_histgram.setToolTip(_translate("MainWindow", "Histgram graphics"))
        self.graphics_view_histgram.setStatusTip(_translate("MainWindow", "Histgram graphics"))
        self.graphics_view_histgram.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Histgram</p></body></html>"))
        self.graphics_view_binary_image.setToolTip(_translate("MainWindow", "Threholded binary image."))
        self.graphics_view_binary_image.setStatusTip(_translate("MainWindow", "Threholded binary image."))
        self.graphics_view_binary_image.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Binary image generated by threshold segmentation, Otsu or max-Entropy methods.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_threshold), _translate("MainWindow", "Threshold"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Input Image"))
        self.line_edit_input_path2.setToolTip(_translate("MainWindow", "Input image path."))
        self.line_edit_input_path2.setStatusTip(_translate("MainWindow", "Input image path."))
        self.pushbutton_input_path_browser2.setToolTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser2.setStatusTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser2.setText(_translate("MainWindow", "..."))
        self.groupbox_filter_processing.setTitle(_translate("MainWindow", "Filter Processing"))
        self.radiobutton_direct01.setToolTip(_translate("MainWindow", "Direction 01 of edge detecting operations."))
        self.radiobutton_direct01.setStatusTip(_translate("MainWindow", "Direction 01 of edge detecting operations."))
        self.radiobutton_direct01.setText(_translate("MainWindow", "Direc1"))
        self.radiobutton_direct02.setToolTip(_translate("MainWindow", "Direction 02 of edge detecting operations."))
        self.radiobutton_direct02.setStatusTip(_translate("MainWindow", "Direction 02 of edge detecting operations."))
        self.radiobutton_direct02.setText(_translate("MainWindow", "Direc2"))
        self.radiobutton_amplitude.setToolTip(_translate("MainWindow", "Amplitude of edge detecting operations."))
        self.radiobutton_amplitude.setStatusTip(_translate("MainWindow", "Amplitude of edge detecting operations."))
        self.radiobutton_amplitude.setText(_translate("MainWindow", "Amp"))
        self.combobox_filters.setToolTip(_translate("MainWindow", "Filter types including three classical edge detection operations, three classical filters and one user definded filter."))
        self.combobox_filters.setStatusTip(_translate("MainWindow", "Filter types including three classical edge detection operations, three classical filters and one user definded filter."))
        self.combobox_filters.setItemText(0, _translate("MainWindow", "Roberts Operator"))
        self.combobox_filters.setItemText(1, _translate("MainWindow", "Prewitt Operator"))
        self.combobox_filters.setItemText(2, _translate("MainWindow", "Sobel Operator"))
        self.combobox_filters.setItemText(3, _translate("MainWindow", "Mean Filter"))
        self.combobox_filters.setItemText(4, _translate("MainWindow", "Median Filter"))
        self.combobox_filters.setItemText(5, _translate("MainWindow", "Gaussian Filter"))
        self.combobox_filters.setItemText(6, _translate("MainWindow", "User-defined Filter"))
        self.label_gaussian_sigma.setText(_translate("MainWindow", "Sigma:"))
        self.slider_gaussian_sigma.setToolTip(_translate("MainWindow", "Slider for setting sigma of guassian filter."))
        self.slider_gaussian_sigma.setStatusTip(_translate("MainWindow", "Slider for setting sigma of guassian filter."))
        self.line_edit_gaussian_sigma.setToolTip(_translate("MainWindow", "Text editor for setting sigma of guassian filter."))
        self.line_edit_gaussian_sigma.setStatusTip(_translate("MainWindow", "Text editor for setting sigma of guassian filter."))
        self.line_edit_gaussian_sigma.setText(_translate("MainWindow", "1.2"))
        self.label_filter_size.setText(_translate("MainWindow", "Size :"))
        self.slider_filter_size.setToolTip(_translate("MainWindow", "Slider for setting filter size."))
        self.slider_filter_size.setStatusTip(_translate("MainWindow", "Slider for setting filter size."))
        self.line_edit_filter_size.setToolTip(_translate("MainWindow", "Text editor for setting filter size."))
        self.line_edit_filter_size.setStatusTip(_translate("MainWindow", "Text editor for setting filter size."))
        self.line_edit_filter_size.setText(_translate("MainWindow", "3"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Export and Output"))
        self.line_edit_export_path2.setToolTip(_translate("MainWindow", "Export image path."))
        self.line_edit_export_path2.setStatusTip(_translate("MainWindow", "Export image path."))
        self.pushbutton_export_path_browser2.setToolTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser2.setStatusTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser2.setText(_translate("MainWindow", "..."))
        self.pushbutton_export2.setToolTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export2.setStatusTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export2.setText(_translate("MainWindow", "Export"))
        self.pushbutton_sendto2.setToolTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto2.setStatusTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto2.setText(_translate("MainWindow", "Send to..."))
        self.pushbutton_reset2.setToolTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset2.setStatusTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset2.setText(_translate("MainWindow", "Reset"))
        self.pushbutton_exit2.setToolTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit2.setStatusTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit2.setText(_translate("MainWindow", "Exit"))
        self.graphics_view_filters_image.setToolTip(_translate("MainWindow", "Filtered image."))
        self.graphics_view_filters_image.setStatusTip(_translate("MainWindow", "Filtered image."))
        self.graphics_view_filters_image.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Binary image generated by threshold segmentation, Otsu or max-Entropy methods.</p></body></html>"))
        self.graphics_view_source_image2.setToolTip(_translate("MainWindow", "Source image."))
        self.graphics_view_source_image2.setStatusTip(_translate("MainWindow", "Source image."))
        self.table_filter.setToolTip(_translate("MainWindow", "Kernel of filter or operator."))
        self.table_filter.setStatusTip(_translate("MainWindow", "Kernel of filter or operator."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Input Image"))
        self.line_edit_input_path3.setToolTip(_translate("MainWindow", "Input image path."))
        self.line_edit_input_path3.setStatusTip(_translate("MainWindow", "Input image path."))
        self.pushbutton_input_path_browser3.setToolTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser3.setStatusTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser3.setText(_translate("MainWindow", "..."))
        self.groupbox_se_processing.setTitle(_translate("MainWindow", "Morph Operation Processing"))
        self.combobox_morph_oper.setToolTip(_translate("MainWindow", "Morphological operations including dilation, erosion, opening and closing."))
        self.combobox_morph_oper.setStatusTip(_translate("MainWindow", "Morphological operations including dilation, erosion, opening and closing."))
        self.combobox_morph_oper.setItemText(0, _translate("MainWindow", "Dilation"))
        self.combobox_morph_oper.setItemText(1, _translate("MainWindow", "Erosion"))
        self.combobox_morph_oper.setItemText(2, _translate("MainWindow", "Open"))
        self.combobox_morph_oper.setItemText(3, _translate("MainWindow", "Close"))
        self.checkbox_show_diff.setToolTip(_translate("MainWindow", "Show difference between source image and result image."))
        self.checkbox_show_diff.setStatusTip(_translate("MainWindow", "Show difference between source image and result image."))
        self.checkbox_show_diff.setText(_translate("MainWindow", "Show Diff"))
        self.combobox_se.setToolTip(_translate("MainWindow", "Structure element types including rectangle, cross, ellipse and user-definded."))
        self.combobox_se.setStatusTip(_translate("MainWindow", "Structure element types including rectangle, cross, ellipse and user-definded."))
        self.combobox_se.setCurrentText(_translate("MainWindow", "Rect SE"))
        self.combobox_se.setItemText(0, _translate("MainWindow", "Rect SE"))
        self.combobox_se.setItemText(1, _translate("MainWindow", "Cross SE"))
        self.combobox_se.setItemText(2, _translate("MainWindow", "Ellipse SE"))
        self.combobox_se.setItemText(3, _translate("MainWindow", "User Defined"))
        self.checkbox_se_regular.setToolTip(_translate("MainWindow", "If checked \'regular\', the width and height of structure element would be the same."))
        self.checkbox_se_regular.setStatusTip(_translate("MainWindow", "If checked \'regular\', the width and height of structure element would be the same."))
        self.checkbox_se_regular.setText(_translate("MainWindow", "Regular"))
        self.label_se_width.setText(_translate("MainWindow", "SE Width :"))
        self.slider_se_width.setToolTip(_translate("MainWindow", "Slider for setting structure element width."))
        self.slider_se_width.setStatusTip(_translate("MainWindow", "Slider for setting structure element width."))
        self.line_edit_se_width.setToolTip(_translate("MainWindow", "Text editor for setting structure element width."))
        self.line_edit_se_width.setStatusTip(_translate("MainWindow", "Text editor for setting structure element width."))
        self.line_edit_se_width.setText(_translate("MainWindow", "5"))
        self.label_se_height.setText(_translate("MainWindow", "SE Height:"))
        self.slider_se_height.setToolTip(_translate("MainWindow", "Slider for setting structure element height."))
        self.slider_se_height.setStatusTip(_translate("MainWindow", "Slider for setting structure element height."))
        self.line_edit_se_height.setToolTip(_translate("MainWindow", "Text editor for setting structure element height."))
        self.line_edit_se_height.setStatusTip(_translate("MainWindow", "Text editor for setting structure element height."))
        self.line_edit_se_height.setText(_translate("MainWindow", "5"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Export and Output"))
        self.line_edit_export_path3.setToolTip(_translate("MainWindow", "Export image path."))
        self.line_edit_export_path3.setStatusTip(_translate("MainWindow", "Export image path."))
        self.pushbutton_export_path_browser3.setToolTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser3.setStatusTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser3.setText(_translate("MainWindow", "..."))
        self.pushbutton_export3.setToolTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export3.setStatusTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export3.setText(_translate("MainWindow", "Export"))
        self.pushbutton_sendto3.setToolTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto3.setStatusTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto3.setText(_translate("MainWindow", "Send to..."))
        self.pushbutton_reset3.setToolTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset3.setStatusTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset3.setText(_translate("MainWindow", "Reset"))
        self.pushbutton_exit3.setToolTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit3.setStatusTip(_translate("MainWindow", "Exit main window."))
        self.pushbutton_exit3.setText(_translate("MainWindow", "Exit"))
        self.graphics_view_morph_oper_image.setToolTip(_translate("MainWindow", "Result image after morphological operation processing."))
        self.graphics_view_morph_oper_image.setStatusTip(_translate("MainWindow", "Result image after morphological operation processing."))
        self.graphics_view_morph_oper_image.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Binary image generated by threshold segmentation, Otsu or max-Entropy methods.</p></body></html>"))
        self.graphics_view_source_image3.setToolTip(_translate("MainWindow", "Source image."))
        self.graphics_view_source_image3.setStatusTip(_translate("MainWindow", "Source image."))
        self.pushbutton_set_origin.setToolTip(_translate("MainWindow", "Set origin of structure element."))
        self.pushbutton_set_origin.setStatusTip(_translate("MainWindow", "Set origin of structure element."))
        self.pushbutton_set_origin.setText(_translate("MainWindow", "Set Origin"))
        self.pushbutton_cancel_set_origin.setToolTip(_translate("MainWindow", "Cancel setting origin of structure element."))
        self.pushbutton_cancel_set_origin.setStatusTip(_translate("MainWindow", "Cancel setting origin of structure element."))
        self.pushbutton_cancel_set_origin.setText(_translate("MainWindow", "Cencel"))
        self.table_se.setToolTip(_translate("MainWindow", "Structure element."))
        self.table_se.setStatusTip(_translate("MainWindow", "Structure element."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_morph_oper), _translate("MainWindow", "Morph Operation"))
        self.graphics_view_morph_funs_image.setToolTip(_translate("MainWindow", "Result image after morphological functions processing."))
        self.graphics_view_morph_funs_image.setStatusTip(_translate("MainWindow", "Result image after morphological functions processing."))
        self.graphics_view_morph_funs_image.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Binary image generated by threshold segmentation, Otsu or max-Entropy methods.</p></body></html>"))
        self.graphics_view_source_image4.setToolTip(_translate("MainWindow", "Source image."))
        self.graphics_view_source_image4.setStatusTip(_translate("MainWindow", "Source image."))
        self.graphics_view_marker.setToolTip(_translate("MainWindow", "A marker. Only used in condiational dilation of binary image."))
        self.graphics_view_marker.setStatusTip(_translate("MainWindow", "A marker. Only used in condiational dilation of binary image."))
        self.combobox_marker_shape.setToolTip(_translate("MainWindow", "Choose marker shape."))
        self.combobox_marker_shape.setStatusTip(_translate("MainWindow", "Choose marker shape."))
        self.combobox_marker_shape.setItemText(0, _translate("MainWindow", "Disk"))
        self.combobox_marker_shape.setItemText(1, _translate("MainWindow", "Vline"))
        self.combobox_marker_shape.setItemText(2, _translate("MainWindow", "Hline"))
        self.pushbutton_set_marker.setToolTip(_translate("MainWindow", "Set marker position on source image."))
        self.pushbutton_set_marker.setStatusTip(_translate("MainWindow", "Set marker position on source image."))
        self.pushbutton_set_marker.setText(_translate("MainWindow", "Set Marker"))
        self.pushbutton_cancel_set_marker.setToolTip(_translate("MainWindow", "Cancel setting marker position on source image."))
        self.pushbutton_cancel_set_marker.setStatusTip(_translate("MainWindow", "Cancel setting marker position on source image."))
        self.pushbutton_cancel_set_marker.setText(_translate("MainWindow", "Cencel"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Input Image"))
        self.line_edit_input_path4.setToolTip(_translate("MainWindow", "Input image path."))
        self.line_edit_input_path4.setStatusTip(_translate("MainWindow", "Input image path."))
        self.pushbutton_input_path_browser4.setToolTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser4.setStatusTip(_translate("MainWindow", "Choose Input image path."))
        self.pushbutton_input_path_browser4.setText(_translate("MainWindow", "..."))
        self.groupbox_morph_funs_processing.setTitle(_translate("MainWindow", "Morph Function Processing"))
        self.checkbox_animation.setToolTip(_translate("MainWindow", "Show animation."))
        self.checkbox_animation.setStatusTip(_translate("MainWindow", "Show animation."))
        self.checkbox_animation.setText(_translate("MainWindow", "Animation"))
        self.radiobutton_skeleton_reconstruction.setToolTip(_translate("MainWindow", "Apply skeleton reconstrution."))
        self.radiobutton_skeleton_reconstruction.setStatusTip(_translate("MainWindow", "Apply skeleton reconstrution."))
        self.radiobutton_skeleton_reconstruction.setText(_translate("MainWindow", "Skeleton Recon"))
        self.radiobutton_distance_transfrom.setToolTip(_translate("MainWindow", "Apply distance transform."))
        self.radiobutton_distance_transfrom.setStatusTip(_translate("MainWindow", "Apply distance transform."))
        self.radiobutton_distance_transfrom.setText(_translate("MainWindow", "Distance Trans"))
        self.radiobutton_skeleton.setToolTip(_translate("MainWindow", "Apply skeleton extraction."))
        self.radiobutton_skeleton.setStatusTip(_translate("MainWindow", "Apply skeleton extraction."))
        self.radiobutton_skeleton.setText(_translate("MainWindow", "Skeleton"))
        self.combobox_distance_trans_mode.setToolTip(_translate("MainWindow", "Choose distance calculating mathods."))
        self.combobox_distance_trans_mode.setStatusTip(_translate("MainWindow", "Choose distance calculating mathods."))
        self.combobox_distance_trans_mode.setCurrentText(_translate("MainWindow", "Chess Board"))
        self.combobox_distance_trans_mode.setItemText(0, _translate("MainWindow", "Chess Board"))
        self.combobox_distance_trans_mode.setItemText(1, _translate("MainWindow", "City Block"))
        self.combobox_distance_trans_mode.setItemText(2, _translate("MainWindow", "Euclidean"))
        self.combobox_morph_reconstrction.setToolTip(_translate("MainWindow", "Choose morphological reconstruction type."))
        self.combobox_morph_reconstrction.setStatusTip(_translate("MainWindow", "Choose morphological reconstruction type."))
        self.combobox_morph_reconstrction.setCurrentText(_translate("MainWindow", "Con-Dilation (WB)"))
        self.combobox_morph_reconstrction.setItemText(0, _translate("MainWindow", "Con-Dilation (WB)"))
        self.combobox_morph_reconstrction.setItemText(1, _translate("MainWindow", "OBR (Gray)"))
        self.combobox_morph_reconstrction.setItemText(2, _translate("MainWindow", "CBR (Gray)"))
        self.radiobutton_edge_detection.setToolTip(_translate("MainWindow", "Apply edge detection by morphological operations."))
        self.radiobutton_edge_detection.setStatusTip(_translate("MainWindow", "Apply edge detection by morphological operations."))
        self.radiobutton_edge_detection.setText(_translate("MainWindow", "Edge Detect"))
        self.combobox_edge_detection.setToolTip(_translate("MainWindow", "Choose edge detection type."))
        self.combobox_edge_detection.setStatusTip(_translate("MainWindow", "Choose edge detection type."))
        self.combobox_edge_detection.setCurrentText(_translate("MainWindow", "Standard"))
        self.combobox_edge_detection.setItemText(0, _translate("MainWindow", "Standard"))
        self.combobox_edge_detection.setItemText(1, _translate("MainWindow", "External"))
        self.combobox_edge_detection.setItemText(2, _translate("MainWindow", "Internal"))
        self.radiobutton_morph_reconstruction.setToolTip(_translate("MainWindow", "Apply morphological reconstruction. If souece image is binary image, conditional dilation would be applied."))
        self.radiobutton_morph_reconstruction.setStatusTip(_translate("MainWindow", "Apply morphological reconstruction. If souece image is binary image, conditional dilation would be applied."))
        self.radiobutton_morph_reconstruction.setText(_translate("MainWindow", "Morph Recon"))
        self.combobox_gradient.setToolTip(_translate("MainWindow", "Choose gradient calculating type."))
        self.combobox_gradient.setStatusTip(_translate("MainWindow", "Choose gradient calculating type."))
        self.combobox_gradient.setCurrentText(_translate("MainWindow", "External Gradient"))
        self.combobox_gradient.setItemText(0, _translate("MainWindow", "External Gradient"))
        self.combobox_gradient.setItemText(1, _translate("MainWindow", "Internal Gradient"))
        self.radiobutton_gradient.setToolTip(_translate("MainWindow", "Apply gradient calculation by morphlogical operations."))
        self.radiobutton_gradient.setStatusTip(_translate("MainWindow", "Apply gradient calculation by morphlogical operations."))
        self.radiobutton_gradient.setText(_translate("MainWindow", "Gradient"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Export and Output"))
        self.line_edit_export_path4.setToolTip(_translate("MainWindow", "Export image path."))
        self.line_edit_export_path4.setStatusTip(_translate("MainWindow", "Export image path."))
        self.pushbutton_export_path_browser4.setToolTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser4.setStatusTip(_translate("MainWindow", "Choose export image path."))
        self.pushbutton_export_path_browser4.setText(_translate("MainWindow", "..."))
        self.pushbutton_export4.setToolTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export4.setStatusTip(_translate("MainWindow", "Export result image."))
        self.pushbutton_export4.setText(_translate("MainWindow", "Export"))
        self.pushbutton_sendto4.setToolTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto4.setStatusTip(_translate("MainWindow", "Send current result image to other page as source image."))
        self.pushbutton_sendto4.setText(_translate("MainWindow", "Send to..."))
        self.pushbutton_reset4.setToolTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset4.setStatusTip(_translate("MainWindow", "Reset to parameters and ui as begining."))
        self.pushbutton_reset4.setText(_translate("MainWindow", "Reset"))
        self.pushbutton_exit4.setToolTip(_translate("MainWindow", "Exit main window"))
        self.pushbutton_exit4.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_morph_funs), _translate("MainWindow", "Morph Function"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionClose.setText(_translate("MainWindow", "Close..."))
        self.actionClose_2.setText(_translate("MainWindow", "Close..."))

from PyQt5 import QtChart
from qtUI.MyGraphicsView import MyGraphicsView
